{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 > 19293", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个很牛逼的测试用例\")\n    def test_3():\n>       assert 0 >19293\nE       assert 0 > 19293\n\nbaog.py:17: AssertionError"}, "start": 1566181523376, "stop": 1566181523376, "uuid": "c35ac25f-6388-4512-a781-0fae9eb79685", "historyId": "e52861d2415524f54efdc456541957ff", "fullName": "baog#test_3", "labels": [{"name": "feature", "value": "模块二"}, {"name": "story", "value": "这是一个很牛逼的测试用例"}, {"name": "parentSuite"}, {"name": "suite", "value": "baog"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-0O5FOI1"}, {"name": "thread", "value": "8476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "baog"}]}